### ISSUE TITLE
能否设置打包后的静态文件与html放在同一文件夹

### ISSUE THREAD

**Issue by pangao66** [Monine/webpack-multi-page#2]
目前打包的html会按照项目结构文件夹创建, 然后生成的css和js都放在了assets文件夹,下面同样安装项目结构文件夹创建,能否把html和静态文件打包到一起? 比如 pageb 打包后 dist pageb下
index.html 然后 ./assets/img ./assets/css ./assets/js 这样的,而不是所有的都打包到了总的assets目录下

**Comment by Monine** [comment]
如果需要这样设置当然是可以的，不过你需要自行配置。

把所有资源放在 assets 目录下是特意这样做的，这样可以方便直接把 assets 目录扔到 CDN 服务器上去，不知道在这点上你是否认同？

**Comment by pangao66** [comment]
放在cdn上当然这样做是最好的,vue-cli默认也是这样的直接/   但是如果不是放在cdn的, 而且如果服务器的路径不是根路径会导致错误,所以我希望能够  每个页面彻底分开,这样把单独一个页面拿出来也能很方便的运行,只有公共的放在顶层assest, 其他每个页面都有自己的assets.  webpack 的配置我不是很懂,可以的话希望能指点一下

**Comment by Monine** [comment]
不太认同你的需求，首先公共资源加载依然是个问题，然后就算前端的页面文件和资源文件没有放在域名所对应的服务器根目录，但总还是在根目录其中某个目录里面是不是？

我再确定一下：
前端的页面文件和资源文件全部放在服务器上，而且不是放在域名对应的服务器根目录，而是根目录其中的某一个子目录里面，是这样的？

**Comment by pangao66** [comment]
对的

**Comment by Monine** [comment]
前端文件全部放入服务器，但不在域名对应根目录，而是其中的某个子目录，那可以通过配置 `config/index.js` 内导出的 `build.assetsPublicPath` 属性解决需求。

e.g.
`build.assetsPublicPath = '/path/to/assets`
