### ISSUE TITLE
关于添加eslint

### ISSUE THREAD

**Issue by Createwj** [Monine/webpack-multi-page#4]
is:issue is:open 你好 我在项目中加进去eslint的时候发现 检测到$符号是未定义  实际上它是全局变量  怎么让eslint不报错  goog半天都没有找到合理解释   希望帮忙解答  万分感谢

**Comment by Monine** [comment]
[Specifying Globals](https://eslint.org/docs/user-guide/configuring#specifying-globals)

在 eslint 的配置文件（比如 .eslintrc.js）内加入如下配置：

```json
{
    "globals": {
        "$": true
    }
}
```
