### ISSUE TITLE
打包

### ISSUE THREAD

**Issue by Createwj** [Monine/webpack-multi-page#5]
打包的时候  首页 和 其他页面引用资源路径不同  必须手动去修改  首页是 ./    其他页面都是../  是这样的吗

**Comment by Monine** [comment]
不需要手动修改，都处理好了。
建议你 clone 或下载此项目，运行打包命令然后查看打包之后的查看资源引用路径是否如你所需。

**Comment by Monine** [comment]
我刚测试并没有发现你所说的资源引用路径问题，能否详细描述一下细节了？

或者你按照我说的方式操作一遍：

1. npm 或 yarn 全局安装 http-server 插件

2. 执行打包命令：`npm run build` 或 `yarn build`

3. 进入 dist 目录（cd dist）然后执行 `http-server` 命令

4. 浏览器打开 `http://localhost:8080`

如果 `http://localhost:8080` 页面没有正常显示或是报错，还请在这留言告知一声，详细描述一下问题，多谢。

**Comment by Createwj** [comment]
可以的  谢谢啦 我去看看我的项目哪里有问题
