### ISSUE TITLE
awardRotate.js 插件的错误

### ISSUE THREAD

**Issue by Createwj** [Monine/webpack-multi-page#6]
1

**Comment by Monine** [comment]
能详细描述下吗？

本地环境开发时报错还是打包后生产环境运行报错？

**Comment by Createwj** [comment]
哎呀 我找到错误了 是es6的锅  那个插件里面有没有声明的变量 然后就会报错  不好意思  顺便请教一下您  我的webstorm已经设置了兼容es6  为什么还是用es6写的代码 webstorm不识别 卸载都重安装了一次了

**Comment by Monine** [comment]
抱歉，没有用过 webstorm，我用 vscode。
