### ISSUE TITLE
 关于 underscore-template-loader 插件 未定义参数报错的问题

### ISSUE THREAD

**Issue by Gert-YXS** [Monine/webpack-multi-page#8]
> 关于 underscore-template-loader 插件

```
<header>
<% if (name) { %>
<h1><%= name %></h1>
<% } %>
</header>
```

 页面a.html
```
@require('path/to/header.html', { "name": 'monine' })
```

页面b.html
```
@require('path/to/header.html')
```

将从HtmlWebpackPlugin抛出错误：
Template execution failed: ReferenceError: name is not defined

这个问题 作者好像没给出解决方案，请问您那边已经解决了吗？
期待您的回复！！！

**Comment by Monine** [comment]
只能告诉你一个简单的的办法：`@require('path/to/header.html', { "name": '' })`
